fix(common): improve yt-dl script

diff --git a/PC/roles/common/files/home/.local/bin/yt-dl b/PC/roles/common/files/home/.local/bin/yt-dl
--- a/PC/roles/common/files/home/.local/bin/yt-dl
+++ b/PC/roles/common/files/home/.local/bin/yt-dl
@@ -1,30 +1,38 @@
-#!/usr/bin/env sh
+#!/bin/bash
 
-[ "$1" ] || exit 1
+# Check if required arguments are provided
+if [ $# -lt 1 ]; then
+	echo "Error: URL is required" >&2
+	exit 1
+fi
 
 # Set default value for max-width if the argument is missing
-max_width=1080
-[ "$2" ] && {
-  max_width="$1"
-  shift 
-}
-url="$1"
-#echo width: $max_width url: $url arg2: $2
-#exit 0
-title=$(yt-dlp -e "$url")
+MAX_WIDTH=${2:-1080}
 
-cd "$HOME/Downloads/youtube-dl" || exit 1
+# Set URL and title
+URL=$1
+TITLE=$(yt-dlp -e "$URL")
 
-dl_op="--external-downloader aria2c --external-downloader-args '-c -j3 -x3 -s3 -k 1M'"
-output='%(uploader)s/%(title)s-%(duration)s-%(resolution)s.%(ext)s'
-format="bestvideo[height<=$max_width]+bestaudio/best"
+# Create download directory if it doesn't exist
+DOWNLOAD_DIR="$HOME/Downloads/youtube-dl"
+mkdir -p "$DOWNLOAD_DIR" || exit 1
 
-while ! {
-	notify-send -u low 'Try to download :' "$title"
-	eval yt-dlp "$dl_op" -o '$output' -f '$format' '$1'
-}; do
-	notify-send -t 5 -u critical 'Fail to download:' "$title"
+# Change directory to download directory
+cd "$DOWNLOAD_DIR" || exit 1
+
+# Define download options and format
+DL_OPTIONS=(
+	--external-downloader aria2c
+	--external-downloader-args '-c -j3 -x3 -s3 -k 1M'
+)
+OUTPUT='%(uploader)s/%(title)s-%(duration)s-%(resolution)s.%(ext)s'
+FORMAT="bestvideo[height<=$MAX_WIDTH]+bestaudio/best"
+
+# Download video in a loop until successful
+while ! yt-dlp "${DL_OPTIONS[@]}" -o "$OUTPUT" -f "$FORMAT" "$URL"; do
+	notify-send -t 5 -u critical "Failed to download: $TITLE"
 	sleep 10
 done
 
-notify-send -u normal 'Video downloaded :' "$title"
+# Send success notification
+notify-send -u normal "Video downloaded: $TITLE"
